version: '2'
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    platform: linux/amd64
    ports:
      - 8000:8000  # Web
      - 8089:8089  # REST API
    environment:
      - TZ=Asia/Tokyo
      - SPLUNK_PASSWORD=password
      - SPLUNK_START_ARGS=--accept-license
